language: python
python:
- "2.7"
install:
- pip install  -r requirements.txt
script:
- flake8 unittest_data_provider
- flake8 test
- python -m unittest discover
- coverage run --source photospicker -m unittest discover
- codecov